-- MySQL Script generated by MySQL Workbench
-- Fri Aug  9 17:26:09 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema energydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema energydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `energydb` DEFAULT CHARACTER SET utf8mb4 ;
USE `energydb` ;

-- -----------------------------------------------------
-- Table `energydb`.`po_action_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`po_action_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `energydb`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `filecode` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `revision` VARCHAR(45) NOT NULL,
  `release_date` DATE NOT NULL,
  `comment` VARCHAR(1000) NOT NULL,
  `drawing` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `energydb`.`state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`state` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `energydb`.`parts_and_assemblies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`parts_and_assemblies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `item_id` INT NOT NULL,
  `serial_number` VARCHAR(45) NULL DEFAULT NULL,
  `state_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_pa_state_idx` (`state_id` ASC) VISIBLE,
  INDEX `fk_pa_item_idx` (`item_id` ASC) VISIBLE,
  CONSTRAINT `fk_pa_item`
    FOREIGN KEY (`item_id`)
    REFERENCES `energydb`.`items` (`id`),
  CONSTRAINT `fk_pa_state`
    FOREIGN KEY (`state_id`)
    REFERENCES `energydb`.`state` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `energydb`.`Assambly_content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`Assambly_content` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `parent_id` INT NOT NULL,
  `child_id` INT NOT NULL,
  `child_quantity` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_parent_idx` (`parent_id` ASC) VISIBLE,
  INDEX `fk_child_idx` (`child_id` ASC) VISIBLE,
  CONSTRAINT `fk_ac_parent`
    FOREIGN KEY (`child_id`)
    REFERENCES `energydb`.`parts_and_assemblies` (`id`),
  CONSTRAINT `fk_ac_child`
    FOREIGN KEY (`parent_id`)
    REFERENCES `energydb`.`parts_and_assemblies` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `energydb`.`location_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`location_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT 'Storage, Hub',
  `comment` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `energydb`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`locations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `comment` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idPartsLocation_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_location_type_idx` (`type_id` ASC) VISIBLE,
  CONSTRAINT `fk_l_type`
    FOREIGN KEY (`type_id`)
    REFERENCES `energydb`.`location_types` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `energydb`.`po`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`po` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idOrders_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `energydb`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`suppliers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `energydb`.`po_content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`po_content` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  `supplier_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `comment` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_order_id_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_supplier_iddd_idx` (`supplier_id` ASC) VISIBLE,
  INDEX `fk_purchase item_idx` (`item_id` ASC) VISIBLE,
  CONSTRAINT `fk_purchase item`
    FOREIGN KEY (`item_id`)
    REFERENCES `energydb`.`items` (`id`),
  CONSTRAINT `fk_purchase_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `energydb`.`po` (`id`),
  CONSTRAINT `fk_purchase_supplier`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `energydb`.`suppliers` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `energydb`.`WO_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`WO_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `energydb`.`wo_templates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`wo_templates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_sot_type_idx` (`type_id` ASC) VISIBLE,
  INDEX `fk_wot_item_idx` (`item_id` ASC) VISIBLE,
  CONSTRAINT `fk_wot_type`
    FOREIGN KEY (`type_id`)
    REFERENCES `energydb`.`WO_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wot_item`
    FOREIGN KEY (`item_id`)
    REFERENCES `energydb`.`items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `energydb`.`wo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`wo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `part_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `template_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idServiceOrderContent_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_part_idx` (`part_id` ASC) VISIBLE,
  INDEX `fk_soc_template_idx` (`template_id` ASC) VISIBLE,
  CONSTRAINT `fk_woc_part`
    FOREIGN KEY (`part_id`)
    REFERENCES `energydb`.`parts_and_assemblies` (`id`),
  CONSTRAINT `fk_woc_template`
    FOREIGN KEY (`template_id`)
    REFERENCES `energydb`.`wo_templates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `energydb`.`toolsets_names`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`toolsets_names` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'таблица имен сборок';


-- -----------------------------------------------------
-- Table `energydb`.`toolset_templates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`toolset_templates` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `toolset_name_id` INT NOT NULL,
  `parent_item_id` INT NOT NULL,
  `child_item_id` INT NOT NULL,
  `child_quantity` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_template_idx` (`toolset_name_id` ASC) VISIBLE,
  INDEX `fk_child_item_idx` (`child_item_id` ASC) VISIBLE,
  INDEX `fk_parent_item_idx` (`parent_item_id` ASC) VISIBLE,
  CONSTRAINT `fk_child_item`
    FOREIGN KEY (`child_item_id`)
    REFERENCES `energydb`.`items` (`id`),
  CONSTRAINT `fk_item_template`
    FOREIGN KEY (`toolset_name_id`)
    REFERENCES `energydb`.`toolsets_names` (`id`),
  CONSTRAINT `fk_parent_item`
    FOREIGN KEY (`parent_item_id`)
    REFERENCES `energydb`.`items` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `energydb`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`user_roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `role_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `energydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `hash` VARCHAR(45) NULL DEFAULT NULL,
  `location_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  INDEX `fk_role_idx` (`role_id` ASC) VISIBLE,
  INDEX `fk_u_location_idx` (`location_id` ASC) VISIBLE,
  CONSTRAINT `fk_u_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `energydb`.`user_roles` (`id`),
  CONSTRAINT `fk_u_location`
    FOREIGN KEY (`location_id`)
    REFERENCES `energydb`.`locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `energydb`.`transfers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`transfers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `part_id` INT NOT NULL,
  `source_location_id` INT NOT NULL,
  `destination_location_id` INT NOT NULL,
  `prev_movement_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_m_source_idx` (`source_location_id` ASC) VISIBLE,
  INDEX `fk_m_destination_idx` (`destination_location_id` ASC) VISIBLE,
  INDEX `fk_m_prev_idx` (`prev_movement_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_source`
    FOREIGN KEY (`source_location_id`)
    REFERENCES `energydb`.`locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_destination`
    FOREIGN KEY (`destination_location_id`)
    REFERENCES `energydb`.`locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_prev`
    FOREIGN KEY (`prev_movement_id`)
    REFERENCES `energydb`.`transfers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `energydb`.`po_actions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`po_actions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_id` INT NOT NULL,
  `target_content_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `executer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pa_order_content_idx` (`target_content_id` ASC) VISIBLE,
  INDEX `fk_pa_type_idx` (`type_id` ASC) VISIBLE,
  INDEX `fk_pa_originator_idx` (`executer_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_pa_order_content`
    FOREIGN KEY (`target_content_id`)
    REFERENCES `energydb`.`po_content` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pa_type`
    FOREIGN KEY (`type_id`)
    REFERENCES `energydb`.`po_action_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pa_ecxecuter`
    FOREIGN KEY (`executer_id`)
    REFERENCES `energydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `energydb`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `energydb`.`wo_action_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`wo_action_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `energydb`.`wo_actions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`wo_actions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_id` INT NOT NULL,
  `wo_id` INT NOT NULL,
  `task_id` INT NULL,
  `executer_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `location_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_sa_target_idx` (`wo_id` ASC) VISIBLE,
  INDEX `fk_sa_originator_idx` (`executer_id` ASC) VISIBLE,
  INDEX `fk_woa_task_idx` (`task_id` ASC) VISIBLE,
  INDEX `fk_woa_type_idx` (`type_id` ASC) VISIBLE,
  INDEX `fk_woa_location_idx` (`location_id` ASC) VISIBLE,
  CONSTRAINT `fk_woa_target`
    FOREIGN KEY (`wo_id`)
    REFERENCES `energydb`.`wo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_woa_executer`
    FOREIGN KEY (`executer_id`)
    REFERENCES `energydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_woa_task`
    FOREIGN KEY (`task_id`)
    REFERENCES `energydb`.`tasks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_woa_type`
    FOREIGN KEY (`type_id`)
    REFERENCES `energydb`.`wo_action_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_woa_location`
    FOREIGN KEY (`location_id`)
    REFERENCES `energydb`.`locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `energydb`.`wo_template_content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`wo_template_content` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `template_id` INT NOT NULL,
  `task_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_sotc_template_idx` (`template_id` ASC) VISIBLE,
  INDEX `fk_sotc_task_idx` (`task_id` ASC) VISIBLE,
  CONSTRAINT `fk_wotc_template`
    FOREIGN KEY (`template_id`)
    REFERENCES `energydb`.`wo_templates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_wotc_task`
    FOREIGN KEY (`task_id`)
    REFERENCES `energydb`.`tasks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `energydb`.`transfer _action_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`transfer _action_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `energydb`.`transfer_content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`transfer_content` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `transfer_id` INT NOT NULL,
  `part_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_mc_movement_idx` (`transfer_id` ASC) VISIBLE,
  INDEX `fk_tc_part_idx` (`part_id` ASC) VISIBLE,
  CONSTRAINT `fk_tc_transfer`
    FOREIGN KEY (`transfer_id`)
    REFERENCES `energydb`.`transfers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tc_part`
    FOREIGN KEY (`part_id`)
    REFERENCES `energydb`.`parts_and_assemblies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `energydb`.`transfer_action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`transfer_action` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_id` INT NOT NULL,
  `target_content_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `executer_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_ma_type_idx` (`type_id` ASC) VISIBLE,
  INDEX `fk_ma_content_idx` (`target_content_id` ASC) VISIBLE,
  INDEX `fk_ta_executer_idx` (`executer_id` ASC) VISIBLE,
  CONSTRAINT `fk_ta_type`
    FOREIGN KEY (`type_id`)
    REFERENCES `energydb`.`transfer _action_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ta_content`
    FOREIGN KEY (`target_content_id`)
    REFERENCES `energydb`.`transfer_content` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ta_executer`
    FOREIGN KEY (`executer_id`)
    REFERENCES `energydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `energydb`.`attribute_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`attribute_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `comment` VARCHAR(500) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `energydb`.`attribute_char_values`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`attribute_char_values` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `attribute_type_id` INT NOT NULL,
  `value` VARCHAR(45) NOT NULL,
  `comment` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_acv_type_idx` (`attribute_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_acv_type`
    FOREIGN KEY (`attribute_type_id`)
    REFERENCES `energydb`.`attribute_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `energydb`.`measure_units`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`measure_units` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `comment` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `energydb`.`attribute_num_values`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`attribute_num_values` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `attribute_type_id` INT NOT NULL,
  `value` FLOAT NOT NULL,
  `unit_id` INT NOT NULL,
  `comment` VARCHAR(300) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_anv_type_idx` (`attribute_type_id` ASC) VISIBLE,
  INDEX `fk_anv_unit_idx` (`unit_id` ASC) VISIBLE,
  CONSTRAINT `fk_anv_type`
    FOREIGN KEY (`attribute_type_id`)
    REFERENCES `energydb`.`attribute_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anv_unit`
    FOREIGN KEY (`unit_id`)
    REFERENCES `energydb`.`measure_units` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `energydb`.`attributes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`attributes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `item_id` INT NOT NULL,
  `attribute_type_id` INT NOT NULL,
  `attribute_num_value_id` INT NOT NULL,
  `attribute_char_value_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_a_item_idx` (`item_id` ASC) VISIBLE,
  INDEX `fk_a_type_idx` (`attribute_type_id` ASC) VISIBLE,
  INDEX `fk_a_num_value_idx` (`attribute_num_value_id` ASC) VISIBLE,
  INDEX `fk_a_char_value_idx` (`attribute_char_value_id` ASC) VISIBLE,
  CONSTRAINT `fk_a_item`
    FOREIGN KEY (`item_id`)
    REFERENCES `energydb`.`items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_a_type`
    FOREIGN KEY (`attribute_type_id`)
    REFERENCES `energydb`.`attribute_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_a_num_value`
    FOREIGN KEY (`attribute_num_value_id`)
    REFERENCES `energydb`.`attribute_num_values` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_a_char_value`
    FOREIGN KEY (`attribute_char_value_id`)
    REFERENCES `energydb`.`attribute_char_values` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `energydb`.`location_structure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `energydb`.`location_structure` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `parent_id` INT NOT NULL,
  `child_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ls_parent_idx` (`parent_id` ASC) VISIBLE,
  INDEX `fk_ls_child_idx` (`child_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_ls_parent`
    FOREIGN KEY (`parent_id`)
    REFERENCES `energydb`.`locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ls_child`
    FOREIGN KEY (`child_id`)
    REFERENCES `energydb`.`locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
